// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZEiX80XsrLY-YQhsUoTIzfpbCa3hcO6c',
    appId: '1:90648976252:web:23a02a1c2170cca354a2f9',
    messagingSenderId: '90648976252',
    projectId: 'silabuz-8954a',
    authDomain: 'silabuz-8954a.firebaseapp.com',
    storageBucket: 'silabuz-8954a.appspot.com',
    measurementId: 'G-4R8PYJ43JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS58OxgP00qvXRVsOcdmdtbi3aLPgu-Hw',
    appId: '1:90648976252:android:cc094fe5e09a162854a2f9',
    messagingSenderId: '90648976252',
    projectId: 'silabuz-8954a',
    storageBucket: 'silabuz-8954a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCycvQkwM6KM1HtZfeYAxpkyzHPPsdaIe4',
    appId: '1:90648976252:ios:e3f103865f4652bb54a2f9',
    messagingSenderId: '90648976252',
    projectId: 'silabuz-8954a',
    storageBucket: 'silabuz-8954a.appspot.com',
    iosClientId: '90648976252-l162jah6bt8kefbgbfcnc3c3kmuk0bn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.sesion1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCycvQkwM6KM1HtZfeYAxpkyzHPPsdaIe4',
    appId: '1:90648976252:ios:e3f103865f4652bb54a2f9',
    messagingSenderId: '90648976252',
    projectId: 'silabuz-8954a',
    storageBucket: 'silabuz-8954a.appspot.com',
    iosClientId: '90648976252-l162jah6bt8kefbgbfcnc3c3kmuk0bn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.sesion1',
  );
}
